#!/usr/bin/env bash
set -euo pipefail

KNOCK_DELAY="${KNOCK_DELAY:-0.25}"
KNOCK_SECRET="${KNOCK_SECRET:-}"
CHECK_TIMEOUT="${CHECK_TIMEOUT:-3}"
CHECK_AFTER_KNOCK=1
VERBOSE=0

usage() {
    cat <<EOF
Usage:
  $(basename "$0") --url 'knockgate://import/v1?...'
  $(basename "$0") --secret SECRET [--check-ports PORTS] SERVER KNOCK_PORT ...
  $(basename "$0") check [--timeout SECONDS] SERVER PORT[/tcp|/udp] ...

Send a KnockGate UDP HMAC knock sequence, then check protected ports.
No root privilege is required.

Options:
  --url URL              Import URL generated by: sudo knockgate qr
  --secret SECRET        Base64url HMAC secret for manual mode
  --check-ports PORTS    Comma-separated protected ports to check after knocking
                         Example: 5432,9092/tcp,51820/udp
  --no-check             Send knock only
  --delay SECONDS        Delay between UDP knock packets. Default: ${KNOCK_DELAY}
  --timeout SECONDS      TCP/UDP check timeout. Default: ${CHECK_TIMEOUT}
  --verbose              Print nc output during checks

Examples:
  $(basename "$0") --url 'knockgate://import/v1?...'
  $(basename "$0") --secret BASE64URL_SECRET --check-ports 5432 SERVER_IP 37708 31114 25880
  $(basename "$0") check SERVER_IP 5432/tcp 5432/udp

Check results:
  OPEN      TCP handshake succeeded.
  REFUSED   TCP path reached host, but no service is listening.
  FILTERED  TCP timed out; usually firewall/network drop.
  UDP-SENT  UDP has no reliable handshake; packet was sent, not proven open.
  FAILED    Local tool or network command failed.
EOF
}

url_decode() {
    local value="${1//+/ }"
    printf '%b' "${value//%/\\x}"
}

query_param() {
    local url="$1"
    local key="$2"
    local query pair name value
    query="${url#*\?}"
    IFS='&' read -r -a pairs <<< "${query}"
    for pair in "${pairs[@]}"; do
        name="${pair%%=*}"
        value="${pair#*=}"
        if [[ "${name}" == "${key}" ]]; then
            url_decode "${value}"
            return 0
        fi
    done
    return 1
}

b64url_to_hex() {
    local input="$1"
    local b64
    b64="${input//-/+}"
    b64="${b64//_//}"
    case $(( ${#b64} % 4 )) in
        2) b64="${b64}==" ;;
        3) b64="${b64}=" ;;
        1) echo "Invalid base64url secret." >&2; return 1 ;;
    esac
    printf '%s' "${b64}" | openssl enc -d -A -base64 | od -An -tx1 | tr -d ' \n'
}

hex_hmac8() {
    local secret_hex="$1"
    local message_hex="$2"
    printf '%s' "${message_hex}" |
        xxd -r -p |
        openssl dgst -sha256 -mac HMAC -macopt "hexkey:${secret_hex}" -binary |
        head -c 8 |
        od -An -tx1 |
        tr -d ' \n'
}

send_udp_text() {
    local server="$1"
    local port="$2"
    local payload="$3"

    if command -v bash >/dev/null 2>&1; then
        PAYLOAD="${payload}" SERVER="${server}" PORT="${port}" bash -c 'printf "%s\n" "$PAYLOAD" >"/dev/udp/$SERVER/$PORT"' 2>/dev/null && return 0
    fi

    if command -v nc >/dev/null 2>&1; then
        printf '%s\n' "${payload}" | nc -u -w1 "${server}" "${port}" >/dev/null 2>&1 || true
        return 0
    fi

    echo "Failed to send UDP packet: bash /dev/udp and nc are unavailable." >&2
    return 1
}

send_udp_hex() {
    local server="$1"
    local port="$2"
    local payload_hex="$3"

    if ! command -v nc >/dev/null 2>&1; then
        echo "Missing nc for binary UDP payload." >&2
        return 1
    fi
    if ! command -v xxd >/dev/null 2>&1; then
        echo "Missing xxd for binary UDP payload." >&2
        return 1
    fi
    printf '%s' "${payload_hex}" | xxd -r -p | nc -u -w1 "${server}" "${port}" >/dev/null 2>&1 || true
}

is_port() {
    [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 1 && $1 <= 65535 ))
}

parse_target() {
    local raw="$1"
    local port proto
    if [[ "${raw}" == */* ]]; then
        port="${raw%/*}"
        proto="${raw##*/}"
    else
        port="${raw}"
        proto="both"
    fi
    proto="$(printf '%s' "${proto}" | tr '[:upper:]' '[:lower:]')"
    if ! is_port "${port}"; then
        echo "Invalid port: ${raw}" >&2
        return 1
    fi
    case "${proto}" in
        tcp|udp|both)
            printf '%s %s\n' "${port}" "${proto}"
            ;;
        *)
            echo "Invalid protocol in ${raw}; use tcp or udp." >&2
            return 1
            ;;
    esac
}

run_nc_with_timeout() {
    local server="$1"
    local port="$2"
    local output_file="$3"
    local pid elapsed=0

    (
        exec nc -vz -w "${CHECK_TIMEOUT}" "${server}" "${port}"
    ) >"${output_file}" 2>&1 &
    pid=$!

    while kill -0 "${pid}" 2>/dev/null; do
        if (( elapsed >= CHECK_TIMEOUT )); then
            kill "${pid}" 2>/dev/null || true
            sleep 0.1
            kill -9 "${pid}" 2>/dev/null || true
            wait "${pid}" 2>/dev/null || true
            printf 'TIMEOUT after %ss\n' "${CHECK_TIMEOUT}" >>"${output_file}"
            return 124
        fi
        sleep 1
        elapsed=$((elapsed + 1))
    done

    wait "${pid}"
}

try_tcp() {
    local server="$1"
    local port="$2"
    local output output_file rc

    output_file="$(mktemp)"
    set +e
    run_nc_with_timeout "${server}" "${port}" "${output_file}"
    rc=$?
    set -e
    output="$(cat "${output_file}")"
    rm -f "${output_file}"

    if [[ "${VERBOSE}" -eq 1 ]]; then
        echo
        echo "== TCP ${server}:${port} =="
        echo "timeout: ${CHECK_TIMEOUT}s"
        printf '%s\n' "${output}"
    fi

    if [[ "${rc}" -eq 0 ]]; then
        echo "OPEN ${server}:${port}/tcp"
    elif printf '%s\n' "${output}" | grep -qi "refused"; then
        echo "REFUSED ${server}:${port}/tcp"
    elif [[ "${rc}" -eq 124 ]] || printf '%s\n' "${output}" | grep -Eqi "timed out|timeout|Operation now in progress"; then
        echo "FILTERED ${server}:${port}/tcp"
    else
        echo "FAILED ${server}:${port}/tcp"
        if [[ "${VERBOSE}" -eq 0 ]]; then
            printf '%s\n' "${output}" >&2
        fi
    fi
}

try_udp() {
    local server="$1"
    local port="$2"
    if command -v nc >/dev/null 2>&1; then
        printf 'knockgate-probe\n' | nc -u -w "${CHECK_TIMEOUT}" "${server}" "${port}" >/dev/null 2>&1 || true
        echo "UDP-SENT ${server}:${port}/udp"
        return 0
    fi
    if command -v bash >/dev/null 2>&1; then
        SERVER="${server}" PORT="${port}" bash -c 'printf "knockgate-probe\n" >"/dev/udp/$SERVER/$PORT"' 2>/dev/null || true
        echo "UDP-SENT ${server}:${port}/udp"
        return 0
    fi
    echo "FAILED ${server}:${port}/udp"
    echo "Missing nc and bash /dev/udp support." >&2
}

check_one() {
    local server="$1"
    local raw="$2"
    local parsed port proto
    parsed="$(parse_target "${raw}")"
    port="${parsed%% *}"
    proto="${parsed##* }"
    case "${proto}" in
        tcp)
            try_tcp "${server}" "${port}"
            ;;
        udp)
            try_udp "${server}" "${port}"
            ;;
        both)
            try_tcp "${server}" "${port}"
            try_udp "${server}" "${port}"
            ;;
    esac
}

check_targets() {
    local server="$1"
    local text="$2"
    local targets target
    if [[ -z "${text}" ]]; then
        echo "No protected ports to check. Use --check-ports PORTS in manual mode." >&2
        return 0
    fi
    echo
    echo "Checking protected ports: ${text}"
    IFS=',' read -r -a targets <<< "${text}"
    for target in "${targets[@]}"; do
        target="$(printf '%s' "${target}" | tr -d '[:space:]')"
        [[ -z "${target}" ]] && continue
        check_one "${server}" "${target}"
    done
}

send_knock() {
    local server="$1"
    local secret="$2"
    shift 2
    local ports=("$@")
    local secret_hex step last_step port ts port_hex step_hex ts_hex nonce_hex message_hex mac_hex payload payload_hex

    if [[ -z "${server}" || -z "${secret}" || "${#ports[@]}" -eq 0 ]]; then
        echo "Missing server, secret, or knock ports." >&2
        usage >&2
        exit 2
    fi
    if ! command -v openssl >/dev/null 2>&1; then
        echo "Missing openssl." >&2
        exit 2
    fi
    if ! command -v xxd >/dev/null 2>&1; then
        echo "Missing xxd." >&2
        exit 2
    fi
    if ! [[ "${KNOCK_DELAY}" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
        echo "Invalid delay: ${KNOCK_DELAY}" >&2
        exit 2
    fi

    for port in "${ports[@]}"; do
        if ! is_port "${port}"; then
            echo "Invalid port: ${port}" >&2
            exit 2
        fi
    done

    secret_hex="$(b64url_to_hex "${secret}")"

    echo "UDP HMAC knocking ${server}: ${ports[*]} (delay ${KNOCK_DELAY}s)"
    step=0
    last_step=$((${#ports[@]} - 1))
    for port in "${ports[@]}"; do
        if (( step == last_step )); then
            ts="$(date +%s)"
            port_hex="$(printf '%04x' "${port}")"
            step_hex="$(printf '%02x' "${step}")"
            ts_hex="$(printf '%08x' "${ts}")"
            nonce_hex="$(openssl rand -hex 4)"
            message_hex="4b31${port_hex}${step_hex}${ts_hex}${nonce_hex}"
            mac_hex="$(hex_hmac8 "${secret_hex}" "${message_hex}")"
            payload_hex="4b31${step_hex}${ts_hex}${nonce_hex}${mac_hex}"
        else
            payload="KG0|${step}"
        fi
        echo "  -> step ${step} ${port}/udp"
        if (( step == last_step )); then
            send_udp_hex "${server}" "${port}" "${payload_hex}"
        else
            send_udp_text "${server}" "${port}" "${payload}"
        fi
        step=$((step + 1))
        sleep "${KNOCK_DELAY}"
    done

    echo "Knock sent."
}

run_check_command() {
    shift
    while [[ "$#" -gt 0 ]]; do
        case "${1}" in
            -h|--help)
                usage
                exit 0
                ;;
            -v|--verbose)
                VERBOSE=1
                shift
                ;;
            -t|--timeout|--timeout-seconds)
                CHECK_TIMEOUT="${2:-}"
                shift 2
                ;;
            --)
                shift
                break
                ;;
            -*)
                echo "Unknown option: ${1}" >&2
                usage >&2
                exit 2
                ;;
            *)
                break
                ;;
        esac
    done
    if [[ "$#" -lt 2 ]]; then
        usage >&2
        exit 2
    fi
    local server="$1"
    shift
    validate_check_timeout
    for target in "$@"; do
        check_one "${server}" "${target}"
    done
}

validate_check_timeout() {
    if ! [[ "${CHECK_TIMEOUT}" =~ ^[0-9]+$ ]] || (( CHECK_TIMEOUT < 1 )); then
        echo "Invalid timeout: ${CHECK_TIMEOUT}" >&2
        exit 2
    fi
}

main() {
    local import_url="" server="" port_text="" protected_ports="" hmac_window=""
    local ports=()

    if [[ "${1:-}" == "check" ]]; then
        run_check_command "$@"
        return
    fi

    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            -h|--help)
                usage
                exit 0
                ;;
            --url)
                import_url="${2:-}"
                shift 2
                ;;
            --secret)
                KNOCK_SECRET="${2:-}"
                shift 2
                ;;
            --check-ports)
                protected_ports="${2:-}"
                shift 2
                ;;
            --no-check)
                CHECK_AFTER_KNOCK=0
                shift
                ;;
            -d|--delay|--delay-seconds)
                KNOCK_DELAY="${2:-}"
                shift 2
                ;;
            -t|--timeout|--timeout-seconds)
                CHECK_TIMEOUT="${2:-}"
                shift 2
                ;;
            -v|--verbose)
                VERBOSE=1
                shift
                ;;
            --)
                shift
                break
                ;;
            -*)
                echo "Unknown option: $1" >&2
                usage >&2
                exit 2
                ;;
            *)
                break
                ;;
        esac
    done

    validate_check_timeout

    if [[ -n "${import_url}" ]]; then
        server="$(query_param "${import_url}" host || true)"
        port_text="$(query_param "${import_url}" knock_ports || true)"
        KNOCK_SECRET="$(query_param "${import_url}" secret || true)"
        hmac_window="$(query_param "${import_url}" hmac_window || true)"
        protected_ports="${protected_ports:-$(query_param "${import_url}" protected_ports || true)}"
        [[ -n "${hmac_window}" ]] && : # kept for import-url compatibility
        IFS=',' read -r -a ports <<< "${port_text}"
    else
        if [[ "$#" -lt 2 ]]; then
            usage >&2
            exit 2
        fi
        server="$1"
        shift
        ports=("$@")
    fi

    send_knock "${server}" "${KNOCK_SECRET}" "${ports[@]}"
    if [[ "${CHECK_AFTER_KNOCK}" -eq 1 ]]; then
        check_targets "${server}" "${protected_ports}"
    fi
}

main "$@"
