package client

import (
	"bufio"
	"context"
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/leconio/knockport/internal/protocol"
)

const (
	ServiceName       = "knockgate-client"
	DefaultInterval   = 300
	DefaultDelay      = 250 * time.Millisecond
	DefaultCheckTime  = 3 * time.Second
	DefaultIPCheckSec = 8
)

var DefaultIPCheckURLs = []string{
	"https://api.ipify.org",
	"http://api.ipify.org",
	"https://checkip.amazonaws.com",
	"http://checkip.amazonaws.com",
	"https://ifconfig.me/ip",
	"http://ifconfig.me/ip",
	"https://cloudflare.com/cdn-cgi/trace",
}

type Import struct {
	Label          string
	Host           string
	KnockPorts     []int
	ProtectedPorts []Target
	Secret         []byte
	SeqTimeout     int
	OpenTimeout    string
	HMACWindow     int
}

type Target struct {
	Port  int
	Proto string
}

type Options struct {
	ImportURL      string
	Interval       int
	IPCheckURLs    []string
	IPCheckTimeout time.Duration
	CheckAfter     bool
	Delay          time.Duration
	CheckTimeout   time.Duration
	Platform       string
	ConfigPath     string
}

type Paths struct {
	Platform string
	Bin      string
	Dir      string
	Config   string
	LastIP   string
	Service  string
	LogFile  string
}

type multiFlag []string

type durationSecondsFlag struct {
	value *time.Duration
}

func (m *multiFlag) String() string {
	return strings.Join(*m, ",")
}

func (m *multiFlag) Set(v string) error {
	*m = append(*m, v)
	return nil
}

func (d durationSecondsFlag) String() string {
	if d.value == nil {
		return ""
	}
	return d.value.String()
}

func (d durationSecondsFlag) Set(v string) error {
	parsed, err := parseFlexibleDuration(v)
	if err != nil {
		return err
	}
	*d.value = parsed
	return nil
}

func Usage(w io.Writer, name, version string) {
	fmt.Fprintf(w, `KnockGate client %s

Usage:
  %s --url 'knockgate://import/v1?...'
  %s --secret SECRET [--check-ports PORTS] SERVER KNOCK_PORT...
  %s check SERVER PORT[/tcp|/udp]...
  %s install --url URL [--interval SECONDS] [--ip-check-url URL]
  %s service-run [--config PATH]
  %s status
  %s logs
  %s uninstall

Commands:
  knock        Send one UDP HMAC knock sequence. This is the default command.
  check        Check protected TCP/UDP ports without knocking.
  install      Install an auto-refresh client service.
  service-run  Run the auto-refresh service loop.
  status       Show installed client service status.
  logs         Show installed client service logs.
  uninstall    Remove the installed client service.

Options:
  --url URL              Import URL generated by the KnockGate server.
  --secret SECRET        Base64url HMAC secret for manual mode.
  --check-ports PORTS    Comma-separated ports to check after knocking.
  --no-check             Send knock only.
  --delay SECONDS        Delay between UDP packets. Default: 0.25.
  --timeout SECONDS      TCP check timeout. Default: 3.
  --verbose              Accepted for shell-client compatibility.
  --interval SECONDS     Auto-knock interval for install. Default: 300.
  --ip-check-url URL     Public IP endpoint for service mode. Can repeat.
  --ip-check-urls URLS   Comma-separated public IP endpoints.
  --ip-check-timeout N   Per-endpoint timeout. Default: 8.
  --platform NAME        auto, systemd, openwrt, or asus-merlin.
  --config PATH          Config path for service-run.

Check results:
  OPEN      端口已开: TCP handshake succeeded.
  REFUSED   端口已开: TCP path reached host, but no service is listening.
  FILTERED  端口未开: TCP timed out or network dropped the packet.
  UDP-SENT  未知状态: UDP packet was sent, not proven open.
  FAILED    未知状态: local/network command failed.
`, version, name, name, name, name, name, name, name, name)
}

func Main(args []string, version string, stdout, stderr io.Writer) int {
	name := filepath.Base(os.Args[0])
	if len(args) == 0 {
		args = []string{"knock"}
	}
	if args[0] == "-h" || args[0] == "--help" {
		Usage(stdout, name, version)
		return 0
	}
	cmd := args[0]
	if strings.HasPrefix(cmd, "-") {
		cmd = "knock"
	} else {
		args = args[1:]
	}

	switch cmd {
	case "knock":
		return runKnock(args, stdout, stderr)
	case "check":
		return runCheck(args, stdout, stderr)
	case "install":
		return runInstall(args, stdout, stderr)
	case "service-run":
		return runService(args, stdout, stderr)
	case "status":
		return runStatus(stdout, stderr)
	case "logs":
		return runLogs(stdout, stderr)
	case "uninstall":
		return runUninstall(stdout, stderr)
	case "help":
		Usage(stdout, name, version)
		return 0
	default:
		fmt.Fprintf(stderr, "Unknown command: %s\n", cmd)
		Usage(stderr, name, version)
		return 2
	}
}

func runKnock(args []string, stdout, stderr io.Writer) int {
	var checkPorts string
	var secretText string
	var verbose bool
	opts := Options{CheckAfter: true, Delay: DefaultDelay, CheckTimeout: DefaultCheckTime}
	fs := newFlagSet("knock", stderr)
	fs.StringVar(&opts.ImportURL, "url", "", "import URL")
	fs.StringVar(&secretText, "secret", "", "base64url HMAC secret")
	fs.StringVar(&checkPorts, "check-ports", "", "ports to check")
	fs.BoolFunc("no-check", "disable checks", func(string) error {
		opts.CheckAfter = false
		return nil
	})
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "delay", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "delay-seconds", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "d", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "timeout", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "timeout-seconds", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "t", "timeout seconds")
	fs.BoolVar(&verbose, "verbose", false, "verbose")
	fs.BoolVar(&verbose, "v", false, "verbose")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	_ = verbose

	var imp Import
	var err error
	if opts.ImportURL != "" {
		imp, err = ParseImport(opts.ImportURL)
		if err != nil {
			fmt.Fprintf(stderr, "Invalid import URL: %v\n", err)
			return 2
		}
	} else {
		rest := fs.Args()
		if secretText == "" || len(rest) < 2 {
			fmt.Fprintln(stderr, "Manual mode requires --secret SECRET SERVER KNOCK_PORT...")
			return 2
		}
		secret, err := base64.RawURLEncoding.DecodeString(secretText)
		if err != nil {
			fmt.Fprintf(stderr, "Invalid secret: %v\n", err)
			return 2
		}
		ports, err := parsePorts(strings.Join(rest[1:], ","))
		if err != nil {
			fmt.Fprintf(stderr, "Invalid knock ports: %v\n", err)
			return 2
		}
		imp = Import{Host: rest[0], KnockPorts: ports, Secret: secret}
	}
	targets := imp.ProtectedPorts
	if checkPorts != "" {
		targets, err = ParseTargets(checkPorts)
		if err != nil {
			fmt.Fprintf(stderr, "Invalid check ports: %v\n", err)
			return 2
		}
	}
	WarnNetworkPath(stdout, imp.Host, firstPort(imp.KnockPorts))
	if err := Knock(stdout, imp, opts.Delay); err != nil {
		fmt.Fprintf(stderr, "Knock failed: %v\n", err)
		return 1
	}
	if opts.CheckAfter && len(targets) > 0 {
		CheckTargets(stdout, imp.Host, targets, opts.CheckTimeout)
	}
	return 0
}

func runCheck(args []string, stdout, stderr io.Writer) int {
	timeout := DefaultCheckTime
	var verbose bool
	fs := newFlagSet("check", stderr)
	fs.Var(durationSecondsFlag{value: &timeout}, "timeout", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &timeout}, "timeout-seconds", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &timeout}, "t", "timeout seconds")
	fs.BoolVar(&verbose, "verbose", false, "verbose")
	fs.BoolVar(&verbose, "v", false, "verbose")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	_ = verbose
	rest := fs.Args()
	if len(rest) < 2 {
		fmt.Fprintln(stderr, "Usage: knockgate-client check SERVER PORT[/tcp|/udp]...")
		return 2
	}
	targets, err := ParseTargets(strings.Join(rest[1:], ","))
	if err != nil {
		fmt.Fprintf(stderr, "Invalid check ports: %v\n", err)
		return 2
	}
	WarnNetworkPath(stdout, rest[0], firstTargetPort(targets))
	CheckTargets(stdout, rest[0], targets, timeout)
	return 0
}

func runInstall(args []string, stdout, stderr io.Writer) int {
	opts := Options{Interval: DefaultInterval, IPCheckURLs: DefaultIPCheckURLs, IPCheckTimeout: DefaultIPCheckSec * time.Second, CheckAfter: true, Delay: DefaultDelay, CheckTimeout: DefaultCheckTime, Platform: "auto"}
	var ipURLs multiFlag
	var ipURLCSV string
	fs := newFlagSet("install", stderr)
	fs.StringVar(&opts.ImportURL, "url", "", "import URL")
	fs.IntVar(&opts.Interval, "interval", DefaultInterval, "interval")
	fs.Var(&ipURLs, "ip-check-url", "public IP check URL")
	fs.StringVar(&ipURLCSV, "ip-check-urls", "", "public IP check URLs")
	fs.Var(durationSecondsFlag{value: &opts.IPCheckTimeout}, "ip-check-timeout", "IP check timeout seconds")
	fs.StringVar(&opts.Platform, "platform", "auto", "platform")
	fs.BoolFunc("no-check", "disable checks", func(string) error {
		opts.CheckAfter = false
		return nil
	})
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "delay", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "delay-seconds", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.Delay}, "d", "delay seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "timeout", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "timeout-seconds", "timeout seconds")
	fs.Var(durationSecondsFlag{value: &opts.CheckTimeout}, "t", "timeout seconds")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if opts.ImportURL == "" {
		fmt.Fprintln(stderr, "install requires --url.")
		return 2
	}
	if opts.Interval < 10 {
		fmt.Fprintln(stderr, "Invalid interval: use at least 10 seconds.")
		return 2
	}
	if _, err := ParseImport(opts.ImportURL); err != nil {
		fmt.Fprintf(stderr, "Invalid import URL: %v\n", err)
		return 2
	}
	if len(ipURLs) > 0 || ipURLCSV != "" {
		opts.IPCheckURLs = splitCSV(append(strings.Split(ipURLCSV, ","), ipURLs...))
	}
	if os.Geteuid() != 0 {
		fmt.Fprintln(stderr, "install must run as root.")
		return 1
	}
	platform, err := DetectPlatform(opts.Platform)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	paths, err := PlatformPaths(platform)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	if err := InstallService(paths, opts); err != nil {
		fmt.Fprintf(stderr, "Install failed: %v\n", err)
		return 1
	}
	fmt.Fprintf(stdout, "Installed KnockGate client service (%s).\nConfig: %s\nCommand: %s\n", platform, paths.Config, paths.Bin)
	return 0
}

func runService(args []string, stdout, stderr io.Writer) int {
	var cfgPath string
	fs := newFlagSet("service-run", stderr)
	fs.StringVar(&cfgPath, "config", "", "config path")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	opts, paths, err := LoadServiceOptions(cfgPath)
	if err != nil {
		fmt.Fprintf(stderr, "Load config failed: %v\n", err)
		return 1
	}
	return ServiceLoop(stdout, stderr, opts, paths)
}

func runStatus(stdout, stderr io.Writer) int {
	paths, err := ExistingPaths()
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return runServiceCommand(stdout, stderr, paths, "status")
}

func runLogs(stdout, stderr io.Writer) int {
	paths, err := ExistingPaths()
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	switch paths.Platform {
	case "systemd":
		return execStream(stdout, stderr, "journalctl", "-u", ServiceName, "-n", "100", "--no-pager")
	case "openwrt":
		return execStream(stdout, stderr, "logread", "-e", ServiceName)
	case "asus-merlin":
		return execStream(stdout, stderr, "tail", "-n", "100", paths.LogFile)
	default:
		fmt.Fprintf(stderr, "Unsupported platform: %s\n", paths.Platform)
		return 1
	}
}

func runUninstall(stdout, stderr io.Writer) int {
	if os.Geteuid() != 0 {
		fmt.Fprintln(stderr, "uninstall must run as root.")
		return 1
	}
	paths, err := ExistingPaths()
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	if err := UninstallService(paths); err != nil {
		fmt.Fprintf(stderr, "Uninstall failed: %v\n", err)
		return 1
	}
	fmt.Fprintf(stdout, "Removed KnockGate client service (%s).\n", paths.Platform)
	return 0
}

func newFlagSet(name string, stderr io.Writer) *flag.FlagSet {
	fs := flag.NewFlagSet(name, flag.ContinueOnError)
	fs.SetOutput(stderr)
	return fs
}

func ParseImport(raw string) (Import, error) {
	u, err := url.Parse(raw)
	if err != nil {
		return Import{}, err
	}
	if u.Scheme != "knockgate" || u.Host != "import" || !strings.HasPrefix(u.Path, "/v1") {
		return Import{}, errors.New("unsupported URL format")
	}
	q := u.Query()
	host := strings.TrimSpace(q.Get("host"))
	if host == "" {
		return Import{}, errors.New("missing host")
	}
	ports, err := parsePorts(q.Get("knock_ports"))
	if err != nil {
		return Import{}, fmt.Errorf("knock_ports: %w", err)
	}
	if len(ports) == 0 {
		return Import{}, errors.New("missing knock_ports")
	}
	secretText := q.Get("secret")
	if secretText == "" {
		return Import{}, errors.New("missing secret")
	}
	secret, err := base64.RawURLEncoding.DecodeString(secretText)
	if err != nil {
		return Import{}, fmt.Errorf("secret: %w", err)
	}
	targets, err := ParseTargets(q.Get("protected_ports"))
	if err != nil {
		return Import{}, fmt.Errorf("protected_ports: %w", err)
	}
	return Import{
		Label:          q.Get("label"),
		Host:           host,
		KnockPorts:     ports,
		ProtectedPorts: targets,
		Secret:         secret,
		SeqTimeout:     atoiDefault(q.Get("seq_timeout"), 10),
		OpenTimeout:    q.Get("open_timeout"),
		HMACWindow:     atoiDefault(q.Get("hmac_window"), 60),
	}, nil
}

func Knock(w io.Writer, imp Import, delay time.Duration) error {
	fmt.Fprintf(w, "UDP HMAC knocking %s: %s (delay %s)\n", imp.Host, joinInts(imp.KnockPorts), delay)
	for i, port := range imp.KnockPorts {
		payload := []byte(fmt.Sprintf("KG0|%d\n", i))
		if i == len(imp.KnockPorts)-1 {
			var err error
			payload, err = protocol.BuildCompact(imp.Secret, port, i, time.Now())
			if err != nil {
				return err
			}
		}
		addr := net.JoinHostPort(imp.Host, strconv.Itoa(port))
		conn, err := net.DialTimeout("udp", addr, 3*time.Second)
		if err != nil {
			return err
		}
		_, writeErr := conn.Write(payload)
		closeErr := conn.Close()
		if writeErr != nil {
			return writeErr
		}
		if closeErr != nil {
			return closeErr
		}
		fmt.Fprintf(w, "  -> step %d %d/udp\n", i, port)
		if i != len(imp.KnockPorts)-1 && delay > 0 {
			time.Sleep(delay)
		}
	}
	fmt.Fprintln(w, "Knock sent.")
	return nil
}

func CheckTargets(w io.Writer, host string, targets []Target, timeout time.Duration) {
	for _, target := range targets {
		switch target.Proto {
		case "udp":
			checkUDP(w, host, target, timeout)
		default:
			checkTCP(w, host, target, timeout)
		}
	}
}

func checkTCP(w io.Writer, host string, target Target, timeout time.Duration) {
	addr := net.JoinHostPort(host, strconv.Itoa(target.Port))
	conn, err := net.DialTimeout("tcp", addr, timeout)
	if err == nil {
		_ = conn.Close()
		fmt.Fprintf(w, "OPEN 端口已开 %s:%d/tcp\n", host, target.Port)
		return
	}
	if isRefused(err) {
		fmt.Fprintf(w, "REFUSED 端口已开 %s:%d/tcp\n", host, target.Port)
		return
	}
	if isTimeout(err) {
		fmt.Fprintf(w, "FILTERED 端口未开 %s:%d/tcp\n", host, target.Port)
		return
	}
	fmt.Fprintf(w, "FAILED 未知状态 %s:%d/tcp %v\n", host, target.Port, err)
}

func checkUDP(w io.Writer, host string, target Target, timeout time.Duration) {
	addr := net.JoinHostPort(host, strconv.Itoa(target.Port))
	conn, err := net.DialTimeout("udp", addr, timeout)
	if err != nil {
		fmt.Fprintf(w, "FAILED 未知状态 %s:%d/udp %v\n", host, target.Port, err)
		return
	}
	_, _ = conn.Write([]byte("knockgate-check"))
	_ = conn.Close()
	fmt.Fprintf(w, "UDP-SENT 未知状态 %s:%d/udp\n", host, target.Port)
}

func ServiceLoop(stdout, stderr io.Writer, opts Options, paths Paths) int {
	if opts.Interval < 10 {
		opts.Interval = DefaultInterval
	}
	ticker := time.NewTicker(time.Duration(opts.Interval) * time.Second)
	defer ticker.Stop()
	for {
		runServiceOnce(stdout, stderr, opts, paths)
		<-ticker.C
	}
}

func runServiceOnce(stdout, stderr io.Writer, opts Options, paths Paths) {
	imp, err := ParseImport(opts.ImportURL)
	if err != nil {
		logLine(stderr, "invalid import URL: %v", err)
		return
	}
	publicIP, err := DetectPublicIPv4(opts.IPCheckURLs, opts.IPCheckTimeout)
	if err != nil {
		logLine(stderr, "public IPv4 check failed: %v", err)
		return
	}
	if err := StrictPublicPath(imp.Host, firstPort(imp.KnockPorts), publicIP); err != nil {
		logLine(stderr, "skip knock: %v", err)
		return
	}
	last := strings.TrimSpace(readSmall(paths.LastIP))
	if last == publicIP {
		logLine(stdout, "public IP unchanged (%s), refreshing knock", publicIP)
	} else {
		logLine(stdout, "public IP changed: %s -> %s", emptyDash(last), publicIP)
	}
	if err := Knock(stdout, imp, opts.Delay); err != nil {
		logLine(stderr, "knock failed: %v", err)
		return
	}
	_ = os.MkdirAll(filepath.Dir(paths.LastIP), 0700)
	_ = os.WriteFile(paths.LastIP, []byte(publicIP+"\n"), 0600)
	if opts.CheckAfter && len(imp.ProtectedPorts) > 0 {
		CheckTargets(stdout, imp.Host, imp.ProtectedPorts, opts.CheckTimeout)
	}
}

func DetectPublicIPv4(urls []string, timeout time.Duration) (string, error) {
	if len(urls) == 0 {
		urls = DefaultIPCheckURLs
	}
	client := http.Client{Timeout: timeout}
	var errs []string
	for _, endpoint := range urls {
		endpoint = strings.TrimSpace(endpoint)
		if endpoint == "" {
			continue
		}
		ctx, cancel := context.WithTimeout(context.Background(), timeout)
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
		if err != nil {
			cancel()
			errs = append(errs, endpoint+": "+err.Error())
			continue
		}
		resp, err := client.Do(req)
		if err != nil {
			cancel()
			errs = append(errs, endpoint+": "+err.Error())
			continue
		}
		body, readErr := io.ReadAll(io.LimitReader(resp.Body, 4096))
		_ = resp.Body.Close()
		cancel()
		if readErr != nil {
			errs = append(errs, endpoint+": "+readErr.Error())
			continue
		}
		ip := firstIPv4(string(body))
		if ip == "" || suspiciousIPv4(ip) {
			errs = append(errs, endpoint+": no public IPv4")
			continue
		}
		return ip, nil
	}
	return "", errors.New(strings.Join(errs, "; "))
}

func StrictPublicPath(host string, port int, publicIP string) error {
	if net.ParseIP(publicIP) == nil || suspiciousIPv4(publicIP) {
		return fmt.Errorf("current address is not public IPv4: %s", publicIP)
	}
	ips, err := net.LookupIP(host)
	if err != nil {
		return fmt.Errorf("cannot resolve host %s: %w", host, err)
	}
	var resolved net.IP
	for _, ip := range ips {
		if v4 := ip.To4(); v4 != nil {
			resolved = v4
			break
		}
	}
	if resolved == nil {
		return fmt.Errorf("host has no IPv4 address: %s", host)
	}
	if suspiciousIPv4(resolved.String()) {
		return fmt.Errorf("%s resolved to private/CGNAT/fake/reserved IP %s", host, resolved)
	}
	ifaceName := routeInterfaceName(resolved.String(), port)
	if ifaceName != "" && suspiciousIface(ifaceName) {
		return fmt.Errorf("route to %s uses %s", host, ifaceName)
	}
	return nil
}

func WarnNetworkPath(w io.Writer, host string, port int) {
	ips, err := net.LookupIP(host)
	if err != nil {
		fmt.Fprintf(w, "WARN: cannot resolve %s: %v\n", host, err)
		return
	}
	var resolved string
	for _, ip := range ips {
		if v4 := ip.To4(); v4 != nil {
			resolved = v4.String()
			break
		}
	}
	if resolved == "" {
		return
	}
	if suspiciousIPv4(resolved) {
		fmt.Fprintf(w, "WARN: %s resolved to %s, which is private/CGNAT/fake-IP/reserved.\n", host, resolved)
		return
	}
	iface := routeInterfaceName(resolved, port)
	if iface != "" && suspiciousIface(iface) {
		fmt.Fprintf(w, "WARN: route to %s uses %s. TUN/VPN/proxy routing can make check results misleading.\n", host, iface)
	}
}

func DetectPlatform(requested string) (string, error) {
	if requested == "" || requested == "auto" {
		if fileExists("/etc/openwrt_release") && dirExists("/etc/init.d") {
			return "openwrt", nil
		}
		if dirExists("/opt/etc/init.d") && dirExists("/opt/bin") {
			return "asus-merlin", nil
		}
		if _, err := exec.LookPath("systemctl"); err == nil && (dirExists("/run/systemd/system") || commandOK("systemctl", "--version")) {
			return "systemd", nil
		}
		return "", errors.New("cannot auto-detect service manager; use --platform systemd, openwrt, or asus-merlin")
	}
	switch requested {
	case "systemd", "openwrt", "asus-merlin":
		return requested, nil
	default:
		return "", fmt.Errorf("unsupported platform: %s", requested)
	}
}

func PlatformPaths(platform string) (Paths, error) {
	switch platform {
	case "systemd":
		return Paths{Platform: platform, Bin: "/usr/local/bin/knockgate-client", Dir: "/etc/knockgate-client", Config: "/etc/knockgate-client/client.conf", LastIP: "/etc/knockgate-client/last_public_ip", Service: "/etc/systemd/system/" + ServiceName + ".service"}, nil
	case "openwrt":
		return Paths{Platform: platform, Bin: "/usr/bin/knockgate-client", Dir: "/etc/knockgate-client", Config: "/etc/knockgate-client/client.conf", LastIP: "/etc/knockgate-client/last_public_ip", Service: "/etc/init.d/" + ServiceName}, nil
	case "asus-merlin":
		return Paths{Platform: platform, Bin: "/opt/bin/knockgate-client", Dir: "/opt/etc/knockgate-client", Config: "/opt/etc/knockgate-client/client.conf", LastIP: "/opt/etc/knockgate-client/last_public_ip", Service: "/opt/etc/init.d/S99" + ServiceName, LogFile: "/opt/var/log/" + ServiceName + ".log"}, nil
	default:
		return Paths{}, fmt.Errorf("unsupported platform: %s", platform)
	}
}

func ExistingPaths() (Paths, error) {
	for _, platform := range []string{"systemd", "openwrt", "asus-merlin"} {
		paths, _ := PlatformPaths(platform)
		if fileExists(paths.Service) || fileExists(paths.Config) {
			return paths, nil
		}
	}
	platform, err := DetectPlatform("auto")
	if err != nil {
		return Paths{}, err
	}
	return PlatformPaths(platform)
}

func InstallService(paths Paths, opts Options) error {
	if err := os.MkdirAll(paths.Dir, 0700); err != nil {
		return err
	}
	self, err := os.Executable()
	if err != nil {
		return err
	}
	if err := copyFile(self, paths.Bin, 0755); err != nil {
		return err
	}
	if err := writeConfig(paths, opts); err != nil {
		return err
	}
	switch paths.Platform {
	case "systemd":
		if err := writeFile(paths.Service, systemdUnit(paths), 0644); err != nil {
			return err
		}
		if err := execCmd("systemctl", "daemon-reload"); err != nil {
			return err
		}
		return execCmd("systemctl", "enable", "--now", ServiceName+".service")
	case "openwrt":
		if err := writeFile(paths.Service, openwrtInit(paths), 0755); err != nil {
			return err
		}
		if err := execCmd(paths.Service, "enable"); err != nil {
			return err
		}
		return execCmd(paths.Service, "restart")
	case "asus-merlin":
		_ = os.MkdirAll("/opt/var/run", 0755)
		_ = os.MkdirAll("/opt/var/log", 0755)
		if err := writeFile(paths.Service, asusInit(paths), 0755); err != nil {
			return err
		}
		return execCmd(paths.Service, "restart")
	default:
		return fmt.Errorf("unsupported platform: %s", paths.Platform)
	}
}

func UninstallService(paths Paths) error {
	switch paths.Platform {
	case "systemd":
		_ = execCmd("systemctl", "disable", "--now", ServiceName+".service")
		_ = os.Remove(paths.Service)
		_ = execCmd("systemctl", "daemon-reload")
	case "openwrt":
		if fileExists(paths.Service) {
			_ = execCmd(paths.Service, "stop")
			_ = execCmd(paths.Service, "disable")
		}
		_ = os.Remove(paths.Service)
	case "asus-merlin":
		if fileExists(paths.Service) {
			_ = execCmd(paths.Service, "stop")
		}
		_ = os.Remove(paths.Service)
	}
	_ = os.Remove(paths.Bin)
	_ = os.RemoveAll(paths.Dir)
	return nil
}

func LoadServiceOptions(path string) (Options, Paths, error) {
	var paths Paths
	if path == "" {
		var err error
		paths, err = ExistingPaths()
		if err != nil {
			return Options{}, Paths{}, err
		}
		path = paths.Config
	} else {
		paths = Paths{Config: path, LastIP: filepath.Join(filepath.Dir(path), "last_public_ip")}
	}
	values, err := readConfig(path)
	if err != nil {
		return Options{}, Paths{}, err
	}
	if paths.Platform == "" {
		paths.Platform = values["PLATFORM"]
	}
	opts := Options{
		ImportURL:      values["URL"],
		Interval:       atoiDefault(values["INTERVAL"], DefaultInterval),
		IPCheckURLs:    splitCSV(strings.Split(values["IP_CHECK_URLS"], ",")),
		IPCheckTimeout: time.Duration(atoiDefault(values["IP_CHECK_TIMEOUT"], DefaultIPCheckSec)) * time.Second,
		CheckAfter:     values["CHECK_AFTER"] != "0",
		Delay:          parseDurationDefault(values["DELAY"], DefaultDelay),
		CheckTimeout:   parseDurationDefault(values["CHECK_TIMEOUT"], DefaultCheckTime),
	}
	if opts.ImportURL == "" {
		return Options{}, Paths{}, errors.New("missing URL in config")
	}
	if len(opts.IPCheckURLs) == 0 {
		opts.IPCheckURLs = DefaultIPCheckURLs
	}
	return opts, paths, nil
}

func writeConfig(paths Paths, opts Options) error {
	var b strings.Builder
	fmt.Fprintf(&b, "PLATFORM=%s\n", paths.Platform)
	fmt.Fprintf(&b, "URL=%s\n", opts.ImportURL)
	fmt.Fprintf(&b, "INTERVAL=%d\n", opts.Interval)
	fmt.Fprintf(&b, "IP_CHECK_URLS=%s\n", strings.Join(opts.IPCheckURLs, ","))
	fmt.Fprintf(&b, "IP_CHECK_TIMEOUT=%d\n", int(opts.IPCheckTimeout.Seconds()))
	if opts.CheckAfter {
		fmt.Fprintln(&b, "CHECK_AFTER=1")
	} else {
		fmt.Fprintln(&b, "CHECK_AFTER=0")
	}
	fmt.Fprintf(&b, "DELAY=%s\n", opts.Delay)
	fmt.Fprintf(&b, "CHECK_TIMEOUT=%s\n", opts.CheckTimeout)
	return writeFile(paths.Config, b.String(), 0600)
}

func readConfig(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	out := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		out[strings.TrimSpace(key)] = strings.TrimSpace(value)
	}
	return out, scanner.Err()
}

func systemdUnit(paths Paths) string {
	return fmt.Sprintf(`[Unit]
Description=KnockGate client auto knock service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s service-run --config %s
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
`, paths.Bin, paths.Config)
}

func openwrtInit(paths Paths) string {
	return fmt.Sprintf(`#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command %s service-run --config %s
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
`, paths.Bin, paths.Config)
}

func asusInit(paths Paths) string {
	return fmt.Sprintf(`#!/bin/sh
PID_FILE=/opt/var/run/%s.pid
LOG_FILE=%s

case "$1" in
	start)
		if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
			exit 0
		fi
		%s service-run --config %s >>"$LOG_FILE" 2>&1 &
		echo $! >"$PID_FILE"
		;;
	stop)
		if [ -f "$PID_FILE" ]; then
			kill "$(cat "$PID_FILE")" 2>/dev/null || true
			rm -f "$PID_FILE"
		fi
		;;
	restart)
		"$0" stop
		sleep 1
		"$0" start
		;;
	status)
		if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
			echo "running"
		else
			echo "stopped"
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
`, ServiceName, paths.LogFile, paths.Bin, paths.Config)
}

func runServiceCommand(stdout, stderr io.Writer, paths Paths, command string) int {
	switch paths.Platform {
	case "systemd":
		return execStream(stdout, stderr, "systemctl", command, ServiceName+".service")
	case "openwrt", "asus-merlin":
		return execStream(stdout, stderr, paths.Service, command)
	default:
		fmt.Fprintf(stderr, "Unsupported platform: %s\n", paths.Platform)
		return 1
	}
}

func execStream(stdout, stderr io.Writer, name string, args ...string) int {
	cmd := exec.Command(name, args...)
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	if err := cmd.Run(); err != nil {
		return 1
	}
	return 0
}

func execCmd(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s failed: %w: %s", name, strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

func commandOK(name string, args ...string) bool {
	return exec.Command(name, args...).Run() == nil
}

func copyFile(src, dst string, mode os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		_ = out.Close()
		return err
	}
	if err := out.Close(); err != nil {
		return err
	}
	return os.Chmod(dst, mode)
}

func writeFile(path, text string, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(text), mode); err != nil {
		return err
	}
	return os.Chmod(path, mode)
}

func parsePorts(text string) ([]int, error) {
	var out []int
	for _, item := range strings.Split(text, ",") {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		p, err := strconv.Atoi(item)
		if err != nil || p < 1 || p > 65535 {
			return nil, fmt.Errorf("invalid port %q", item)
		}
		out = append(out, p)
	}
	return out, nil
}

func ParseTargets(text string) ([]Target, error) {
	var out []Target
	for _, item := range strings.Split(text, ",") {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		portText, proto, ok := strings.Cut(item, "/")
		if !ok {
			proto = "tcp"
		}
		proto = strings.ToLower(strings.TrimSpace(proto))
		if proto != "tcp" && proto != "udp" {
			return nil, fmt.Errorf("invalid protocol %q", proto)
		}
		p, err := strconv.Atoi(strings.TrimSpace(portText))
		if err != nil || p < 1 || p > 65535 {
			return nil, fmt.Errorf("invalid port %q", portText)
		}
		out = append(out, Target{Port: p, Proto: proto})
	}
	return out, nil
}

func splitCSV(values []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, value := range values {
		for _, item := range strings.Split(value, ",") {
			item = strings.TrimSpace(item)
			if item != "" && !seen[item] {
				seen[item] = true
				out = append(out, item)
			}
		}
	}
	return out
}

func atoiDefault(text string, fallback int) int {
	n, err := strconv.Atoi(strings.TrimSpace(text))
	if err != nil {
		return fallback
	}
	return n
}

func parseDurationDefault(text string, fallback time.Duration) time.Duration {
	if text == "" {
		return fallback
	}
	if d, err := parseFlexibleDuration(text); err == nil {
		return d
	}
	return fallback
}

func parseFlexibleDuration(text string) (time.Duration, error) {
	text = strings.TrimSpace(text)
	if text == "" {
		return 0, errors.New("empty duration")
	}
	if d, err := time.ParseDuration(text); err == nil {
		return d, nil
	}
	f, err := strconv.ParseFloat(text, 64)
	if err != nil {
		return 0, err
	}
	return time.Duration(f * float64(time.Second)), nil
}

func firstIPv4(text string) string {
	re := regexp.MustCompile(`(?:\d{1,3}\.){3}\d{1,3}`)
	for _, match := range re.FindAllString(text, -1) {
		ip := net.ParseIP(match)
		if ip != nil && ip.To4() != nil {
			return ip.To4().String()
		}
	}
	return ""
}

func suspiciousIPv4(ipText string) bool {
	ip := net.ParseIP(ipText).To4()
	if ip == nil {
		return true
	}
	a, b := ip[0], ip[1]
	switch {
	case a == 0, a == 10, a == 127:
		return true
	case a == 100 && b >= 64 && b <= 127:
		return true
	case a == 169 && b == 254:
		return true
	case a == 172 && b >= 16 && b <= 31:
		return true
	case a == 192 && b == 0:
		return true
	case a == 192 && b == 168:
		return true
	case a == 198 && (b == 18 || b == 19):
		return true
	case a >= 224:
		return true
	default:
		return false
	}
}

func routeInterfaceName(ipText string, port int) string {
	if port <= 0 {
		port = 53
	}
	conn, err := net.DialTimeout("udp", net.JoinHostPort(ipText, strconv.Itoa(port)), time.Second)
	if err != nil {
		return ""
	}
	local, _ := conn.LocalAddr().(*net.UDPAddr)
	_ = conn.Close()
	if local == nil {
		return ""
	}
	ifaces, err := net.Interfaces()
	if err != nil {
		return ""
	}
	for _, iface := range ifaces {
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, addr := range addrs {
			if containsIP(addr, local.IP) {
				return iface.Name
			}
		}
	}
	return ""
}

func containsIP(addr net.Addr, ip net.IP) bool {
	switch v := addr.(type) {
	case *net.IPNet:
		return v.Contains(ip)
	case *net.IPAddr:
		return v.IP.Equal(ip)
	default:
		return false
	}
}

func suspiciousIface(name string) bool {
	name = strings.ToLower(name)
	prefixes := []string{"tun", "tap", "utun", "wg", "tailscale", "zt", "clash", "mihomo", "sing", "vpn"}
	for _, p := range prefixes {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	return false
}

func isRefused(err error) bool {
	text := strings.ToLower(err.Error())
	return strings.Contains(text, "connection refused") || strings.Contains(text, "actively refused")
}

func isTimeout(err error) bool {
	var ne net.Error
	if errors.As(err, &ne) && ne.Timeout() {
		return true
	}
	text := strings.ToLower(err.Error())
	return strings.Contains(text, "timeout") || strings.Contains(text, "i/o timeout")
}

func logLine(w io.Writer, format string, args ...any) {
	fmt.Fprintf(w, "%s %s\n", time.Now().Format(time.RFC3339), fmt.Sprintf(format, args...))
}

func readSmall(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	if len(data) > 4096 {
		data = data[:4096]
	}
	return string(data)
}

func emptyDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

func fileExists(path string) bool {
	st, err := os.Stat(path)
	return err == nil && !st.IsDir()
}

func dirExists(path string) bool {
	st, err := os.Stat(path)
	return err == nil && st.IsDir()
}

func firstPort(ports []int) int {
	if len(ports) == 0 {
		return 53
	}
	return ports[0]
}

func firstTargetPort(targets []Target) int {
	if len(targets) == 0 {
		return 53
	}
	return targets[0].Port
}

func joinInts(values []int) string {
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, strconv.Itoa(v))
	}
	return strings.Join(parts, " ")
}
